import React, { useState } from 'react';
import { ThumbsUp, AlertTriangle, Flame, CheckCircle2, Copy, Check, Volume2, VolumeX, ShieldCheck, Sparkles, Award } from 'lucide-react';
import { RoastResult } from '../types';

interface ResultsSectionProps {
  result: RoastResult;
  onOpenTips: () => void;
  onReset: () => void;
}

export const ResultsSection: React.FC<ResultsSectionProps> = ({
  result,
  onOpenTips,
  onReset,
}) => {
  const [copied, setCopied] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(`🔥 RESUME ROAST VERDICT: ${result.verdict}\n\nSCORE: ${result.score}/100\n\nTHE ROAST:\n${result.roast}\n\nGenerated by Resume Roaster`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSpeech = () => {
    if ('speechSynthesis' in window) {
      if (isSpeaking) {
        window.speechSynthesis.cancel();
        setIsSpeaking(false);
      } else {
        window.speechSynthesis.cancel();
        const utterance = new SpeechSynthesisUtterance(result.roast);
        utterance.rate = 1.0;
        utterance.pitch = 0.9;
        utterance.onend = () => setIsSpeaking(false);
        utterance.onerror = () => setIsSpeaking(false);
        setIsSpeaking(true);
        window.speechSynthesis.speak(utterance);
      }
    } else {
      alert('Text-to-speech is not supported in this browser.');
    }
  };

  // Color determination based on score
  const getScoreColor = (score: number) => {
    if (score >= 75) return 'text-emerald-400 border-emerald-500/40 bg-emerald-500/10';
    if (score >= 50) return 'text-amber-400 border-amber-500/40 bg-amber-500/10';
    return 'text-red-400 border-red-500/40 bg-red-500/10';
  };

  return (
    <section id="results-section" className="w-full max-w-6xl mx-auto py-12 px-4 transition-all duration-500 animate-fadeIn">
      {/* Top Score Banner */}
      <div className="glass-panel rounded-3xl p-6 md:p-8 mb-10 border border-white/15 relative overflow-hidden flex flex-col md:flex-row items-center justify-between gap-6 shadow-2xl">
        <div className="flex items-center gap-5">
          {/* Score Badge */}
          <div className={`w-24 h-24 rounded-2xl border-2 flex flex-col items-center justify-center p-2 shadow-inner ${getScoreColor(result.score)}`}>
            <span className="text-3xl font-extrabold font-display leading-none">{result.score}</span>
            <span className="text-[10px] uppercase font-bold tracking-widest text-slate-400 mt-1">/ 100</span>
          </div>

          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xs font-extrabold uppercase tracking-widest text-orange-400 flex items-center gap-1">
                <Award className="w-3.5 h-3.5" /> Official Roast Verdict
              </span>
              {result.isAiGenerated && (
                <span className="px-2 py-0.5 rounded-md bg-purple-500/20 text-purple-300 border border-purple-500/30 text-[10px] font-bold uppercase">
                  Gemini AI
                </span>
              )}
            </div>
            <h2 className="text-2xl md:text-3xl font-extrabold text-white uppercase tracking-tight font-display">
              "{result.verdict}"
            </h2>
            <div className="flex flex-wrap items-center gap-4 mt-3 text-xs text-slate-300 font-medium">
              <span className="bg-slate-900/80 px-2.5 py-1 rounded-lg border border-white/10">
                ⚡ Buzzword Density: <strong className="text-orange-400">{result.funnyStats.buzzwordDensity}</strong>
              </span>
              <span className="bg-slate-900/80 px-2.5 py-1 rounded-lg border border-white/10">
                🎯 ATS Survival: <strong className="text-amber-400">{result.funnyStats.survivalChance}</strong>
              </span>
              <span className="bg-slate-900/80 px-2.5 py-1 rounded-lg border border-white/10">
                ⏱️ Recruiter Skim Time: <strong className="text-emerald-400">{result.funnyStats.recruiterSkimTime}</strong>
              </span>
            </div>
          </div>
        </div>

        {/* Action Controls */}
        <div className="flex flex-wrap items-center gap-3">
          <button
            onClick={onOpenTips}
            className="px-4 py-2.5 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 hover:bg-emerald-500/30 transition-all text-xs font-bold uppercase flex items-center gap-2 cursor-pointer shadow-lg"
          >
            <ShieldCheck className="w-4 h-4" />
            Fix My Resume
          </button>
          <button
            onClick={onReset}
            className="px-4 py-2.5 rounded-full bg-slate-800/80 text-slate-300 border border-white/10 hover:text-white hover:bg-slate-700/80 transition-all text-xs font-bold uppercase flex items-center gap-2 cursor-pointer"
          >
            <Sparkles className="w-4 h-4 text-orange-400" />
            Roast Another
          </button>
        </div>
      </div>

      {/* 3 Distinct Glassmorphic Cards (Side by Side on Desktop) */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-stretch">
        
        {/* Card 1: PROS (Green Tinted Glass) */}
        <div className="glass-card-pros rounded-3xl overflow-hidden flex flex-col transition-all duration-300 hover:-translate-y-1">
          <div className="bg-emerald-950/40 p-5 flex items-center gap-3 border-b border-emerald-500/20">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/20 flex items-center justify-center text-emerald-400 border border-emerald-500/30 shadow-md">
              <ThumbsUp className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white uppercase font-display leading-tight">
                PROS: The Glimmers of Genius
              </h3>
              <span className="text-[11px] text-emerald-400 font-medium">What actually worked well</span>
            </div>
          </div>

          <div className="p-6 flex-grow flex flex-col justify-between">
            <ul className="space-y-4 text-sm text-slate-200">
              {result.pros.map((pro, idx) => (
                <li key={idx} className="flex items-start gap-3">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 mt-0.5 shrink-0" />
                  <span className="leading-snug">{pro}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Card 2: CONS (Yellow/Orange Tinted Glass) */}
        <div className="glass-card-cons rounded-3xl overflow-hidden flex flex-col transition-all duration-300 hover:-translate-y-1">
          <div className="bg-amber-950/40 p-5 flex items-center gap-3 border-b border-amber-500/20">
            <div className="w-10 h-10 rounded-xl bg-amber-500/20 flex items-center justify-center text-amber-400 border border-amber-500/30 shadow-md">
              <AlertTriangle className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white uppercase font-display leading-tight">
                CONS: Room for (Much) Improvement
              </h3>
              <span className="text-[11px] text-amber-400 font-medium">Red flags &amp; missing impact</span>
            </div>
          </div>

          <div className="p-6 flex-grow flex flex-col justify-between">
            <ul className="space-y-4 text-sm text-slate-200">
              {result.cons.map((con, idx) => (
                <li key={idx} className="flex items-start gap-3">
                  <span className="text-amber-400 font-bold shrink-0 mt-0.5">▶</span>
                  <span className="leading-snug">{con}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Card 3: THE ROAST (Red/Pink Tinted Glass - Prominent & Larger) */}
        <div className="glass-card-roast rounded-3xl overflow-hidden flex flex-col lg:scale-105 transition-all duration-300 hover:-translate-y-1 border.2 border-red-500/50 shadow-2xl relative">
          <div className="bg-gradient-to-r from-red-950/80 via-orange-950/60 to-red-950/80 p-5 flex items-center justify-between border-b border-red-500/30">
            <div className="flex items-center gap-3">
              <div className="w-11 h-11 rounded-xl bg-red-500/30 flex items-center justify-center text-red-400 border border-red-500/40 shadow-lg relative">
                <Flame className="w-6 h-6 animate-flame text-orange-400" />
                <span className="absolute -bottom-1 -right-1 text-xs">😂</span>
              </div>
              <div>
                <h3 className="text-lg font-black text-white uppercase font-display leading-tight flex items-center gap-1.5">
                  THE ROAST: Brace for Impact! 🔥
                </h3>
                <span className="text-[11px] text-red-300 font-semibold">Brutal truth with zero filter</span>
              </div>
            </div>
          </div>

          <div className="p-6 flex-grow flex flex-col justify-between space-y-6">
            <p className="text-slate-100 text-sm md:text-base leading-relaxed font-normal bg-black/30 p-4 rounded-2xl border border-red-500/20 italic">
              "{result.roast}"
            </p>

            {/* Bottom Card Footer Actions */}
            <div className="pt-3 border-t border-red-500/20 flex items-center justify-between gap-2">
              <button
                onClick={handleSpeech}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold uppercase transition-all flex items-center gap-1.5 ${
                  isSpeaking
                    ? 'bg-red-500 text-white animate-pulse'
                    : 'bg-red-500/20 text-red-300 hover:bg-red-500/30 border border-red-500/30'
                }`}
              >
                {isSpeaking ? <VolumeX className="w-3.5 h-3.5" /> : <Volume2 className="w-3.5 h-3.5" />}
                {isSpeaking ? 'Stop Reading' : 'Read Out Loud'}
              </button>

              <button
                onClick={handleCopy}
                className="px-3 py-1.5 rounded-xl bg-slate-900/80 text-slate-300 hover:text-white hover:bg-slate-800 border border-white/10 text-xs font-bold uppercase flex items-center gap-1.5 transition-all"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'Copied!' : 'Copy Roast'}
              </button>
            </div>
          </div>
        </div>

      </div>
    </section>
  );
};
